### ISSUE TITLE
Crash function when create payment document by square

### ISSUE THREAD

**Issue by mogmet** [google-pay/firebase-extension#3]
Hi.
I try "Make Payments with Google Pay".
When I created this document.
![image](https://user-images.githubusercontent.com/1166342/141985429-634ba142-35a2-436e-837d-53d7505d658f.png)

Cloud functions was crashed.
![スクリーンショット 2021-11-16 21 26 07](https://user-images.githubusercontent.com/1166342/141985513-d7debe85-d583-4bbf-878d-abe6b6106d3e.png)

Cloud functions says payment token should be string.
But I put json by string.
Why this functions occur error?

**Comment by stephenmcd** [comment]
Valid payment tokens for Square should be strings (they are prefixed with "cnon:" and look like this: "cnon:<characters>"), but the token you're getting from the Google Pay API and then using is a JSON object, which will occur when you're not passing the correct information in the client-side payment request.

If you follow the this guide you should be able to get valid tokens:

https://developer.squareup.com/docs/payment-form/add-digital-wallets/google-pay
